core/blog/api/v1/urls.py
from rest_framework.routers import DefaultRouter

from .views import *

app_name = "api-v1"

router = DefaultRouter()
router.register(r"post", PostModelViewSet, basename="post")
router.register(r"category", CategoryModelViewSet, basename="category")
urlpatterns = router.urls

core/blog/urls.py
from django.urls import include, path

from .views import *

app_name = "blog"

urlpatterns = [
    path("post/", PostListView.as_view(), name="post-list"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("post/create/", PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/edit/", PostEditView.as_view(), name="post-edit"),
    path("post/<int:pk>/delete", PostDeletView.as_view(), name="post-delete"),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="this is a test API",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="amirrezayi0101@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]


# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.urls import reverse

# getting user model


class Post(models.Model):
    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.content[:10] + "..."

    def get_absolute_url(self):
        return reverse("blog:api-v1:post-detail", kwargs={"pk": self.pk})


class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ["image", "author"]

core/blog/api/v1/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from ...models import Category, Post
from .paginations import LargeResultsSetPagination
from .permissions import IsOwnerOrReadOnly
from .serializer import CategorySerializer, PostSerializer


class PostModelViewSet(viewsets.ModelViewSet, IsOwnerOrReadOnly):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["category", "author", "status"]
    search_fields = ["title", "content"]
    ordering_fields = ["published_date"]
    pagination_class = LargeResultsSetPagination


class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

core/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .forms import PostForm
from .models import Post


class PostListView(LoginRequiredMixin, ListView):
    model = Post

    context_object_name = "posts"
    ordering = "id"
    # paginate_by = 2

    # def get_queryset(self):
    #     posts = Post.objects.filter(status=False)
    #     return posts


class PostDetailView(DeleteView):
    model = Post


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post/"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostEditView(UpdateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post/"


class PostDeletView(DeleteView):
    model = Post
    success_url = "/blog/post/"
    template_name = "blog/delete.html"


@api_view()
def api_post_lits_view(request):
    return Response("hello world")

core/templates/blog/delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete</title>
</head>

<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
</body>

</html>

core/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>{{object.title}}</h1>
    <hr>

    <small>{{object.author}} - {{object.published_date}} </small>
    <p>{{object.content}}</p>
    <a href="{% url 'blog:post-list' %}">
        <p>back</p>
    </a>

</body>

</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create</title>
</head>

<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>

</html>

core/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>blog posts</h1>
    <ol>
        {% for post in posts %}
        <li>
            <a href="{% url 'blog:post-detail' pk=post.id %}">
                <h2> {{post.id}} -{{post.title}}</h2>
            </a>
            <a href="{% url 'blog:post-delete' pk=post.id %}">
                <h5>Delete</h5>
            </a>
            <a href="{% url 'blog:post-edit' pk=post.id %}">
                <h5>Edit</h5>
            </a>
            <small>{{post.author.first_name}} {{post.author.last_name}}- {{post.published_date}}</small>
        </li>
        {% endfor %}
    </ol>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    <div style="position: fixed; top: 20px; right: 20px; z-index: 1000;"
        class="bg-blue-600 text-white p-4 rounded-lg shadow-lg">
        <a href="{% url 'blog:post-create' %}">
            <h2>create post</h2>
        </a>
    </div>

</body>

</html>